apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-react-java
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/preyelg/gitops-react-java.git
    targetRevision: deployment
    path: hel
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
