replicaCount: 2

image:
  repository: preyelg/spring-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  host: backend.example.com
