replicaCount: 2

namespace: backend

image:
  repository: preyelg/java-backend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: alb
  host: backend.example.com
