apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend-chart.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "backend-chart.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "backend-chart.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
    image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
    imagePullPolicy: {{ .Values.image.pullPolicy }}
    ports:
      - containerPort: {{ .Values.service.port }}
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: {{ .Values.service.port }}
      initialDelaySeconds: 15
      periodSeconds: 10
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: {{ .Values.service.port }}
      initialDelaySeconds: 30
      periodSeconds: 20

          